name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Update APT
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install --assume-yes git build-essential gettext
      - name: Checkout ECheck
        uses: actions/checkout@v2
        with:
          repository: eressea/echeck
      - name: Build and Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
          run-test: true
          ctest-options: --output-on-failure
      - name: Build Package
        uses: dawidd6/action-debian-package@v1
        with:
           #source_direcory: .
           artifacts_directory: dist/bullseye
           os_distribution: bullseye
           cpu_architecture: i386
      - name: Upload to Packagecloud
        uses: TykTechnologies/packagecloud-action@v1
        with:
          repo: enno/eressea
          dir: dist/bullseye
          debvers: bullseye
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
