name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install --assume-yes git cmake build-essential gettext
      - name: Checkout ECheck
        uses: actions/checkout@v2
        with:
          repository: eressea/echeck
      - name: CI Tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: build
          cmakeoptions: '--config Release'
          ctestoptions: ''

                        
