name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install --assume-yes git cmake build-essential gettext
      - name: Checkout ECheck
        uses: actions/checkout@v2
        with:
          repository: eressea/echeck
      - name: Build and Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
          run-test: true
          ctest-options: --output-on-failure

