name: build-packages
on: [push]

jobs:
  bullseye-package-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ECheck
        uses: actions/checkout@v3
        with:
          repository: eressea/echeck
      - name: Build Package
        uses: dawidd6/action-debian-package@v1
        with:
           #source_direcory: .
           artifacts_directory: dist/bullseye
           os_distribution: bullseye
           cpu_architecture: amd64
      - name: Deploy to packagecloud.io
        uses: lpenz/ghaction-packagecloud@v0.4
        with:
          repository: enno/eressea/debian/bullseye
          directory: dist/bullseye
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
