name: release
on:
  push:
    branch:
      - pkgcloud
#  push:
#    tags:
#      - 'v*'
jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - buster
          - bullseye
        arch:
          - i386
          - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: eressea/echeck
      - name: Build Debian Package
        uses: dawidd6/action-debian-package@v1
        with:
           artifacts_directory: dist/${{ matrix.dist }}
           os_distribution: bullseye
           cpu_architecture: ${{ matrix.arch }}
      - name: Upload to Packagecloud
        uses: danielmundi/upload-packagecloud@v1
        run:
          working-directory: dist/${{ matrix.dist }}
        with:
          PACKAGE-NAME: echeck
          PACKAGECLOUD-REPO: enno/eressea
          PACKAGECLOUD-DISTRIB: debian/${{ matrix.dist }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
