name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - gh
jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - buster
          - bullseye
        arch:
          - i386
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: eressea/echeck
      - name: Build Debian Package
        uses: dawidd6/action-debian-package@v1.5
        with:
           os_distribution: ${{ matrix.dist }}
           cpu_architecture: ${{ matrix.arch }}
           artifacts_directory: artifacts
      - name: Upload to Packagecloud
        if: matrix.dist != 'buster' || matrix.arch != 'arm64'
        continue-on-error: true
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: artifacts/echeck_*.deb
          packagecloud-username: enno
          packagecloud-repo: eressea
          packagecloud-distrib: debian/${{ matrix.dist }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
