name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - gh
jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - bullseye
        arch:
          - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          repository: eressea/echeck
      - name: Build Debian Package
        uses: dawidd6/action-debian-package@latest
        with:
           os_distribution: ${{ matrix.dist }}
           cpu_architecture: ${{ matrix.arch }}
           artifacts_directory: artifacts
      - name: Upload to Packagecloud
        continue-on-error: true
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: artifacts/echeck_*_${{ matrix.arch }}.deb
          packagecloud-username: enno
          packagecloud-repo: eressea
          packagecloud-distrib: debian/${{ matrix.dist }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
